# Site settings
title: "Van Chan Ngo"
email: chan.ngo2203@gmail.com
description: "Ngo's personal page and notes on programming"
baseurl: ""
url: "http://channgo2203.github.io"
title_description: "School of Computer Science, CMU"
title_image: "http://channgo2203.github.io/images/logo.png"
google_analytics: "UA-89119753-1"
disqus_account: channgo
github_repository: https://github.com/channgo2203
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: channgo2203
github_username:  channgo2203
instagram_username:
reddit_username:
linkedin_link: https://www.linkedin.com/in/channgo2203
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: "Created by <a href=\"mailto:chan.ngo2203@gmail.com\">Van Chan Ngo</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/channgo2203\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: :compressed

permalink: pretty
exclude: [vendor]
